server:
  port: 5001
spring:
  datasource:
#    url: jdbc:log4jdbc:h2:file:~/.h2/testdb
#    username: sa
#    password: 123456
#    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.1.114:3306/test?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  thymeleaf:
    cache: false
logging:
  config: classpath:log4j2.xml