server:
  port: 5001
spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:TEST #内存类型数据库
    username: sa
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
  h2:
    console:
      path: /h2-console  #web控制台路径
      enabled: true #开启web控制台
      settings:
        web-allow-others: true #允许远程访问
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  thymeleaf:
    cache: false
