server:
  port: 5000
spring:
  datasource:
    url: jdbc:log4jdbc:h2:file:~/.h2/testdb
    username: sa
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  thymeleaf:
    cache: false
logging:
  config: classpath:log4j2.xml