server:
  port: 5000
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
logging:
  config: classpath:log4j2.xml